spring:
  application:
    name: notification-service
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: chowder
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
server:
  port: 8383
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone : http://${eureka.instance.hostname}:8761/eureka/

security:
  basic:
    enabled: false
  oauth2:
    resource:
      token-info-uri: http://authentication-service/oauth/check_token
    client:
      client-id: chrisx
      client-secret: pascal2023

